# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 NVIDIA Corporation

"""
Defines the omegaconf .yaml configuration format for Alpasim runtime.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Type, TypeVar, cast

import yaml
from alpasim_utils.scenario import VehicleConfig
from omegaconf import MISSING, OmegaConf

C = TypeVar("C")


def typed_parse_config(path: str, config_type: Type[C]) -> C:
    """Reads a yaml file at `path` and parses it into a provided type using omegaconf."""
    with open(path, "r") as yaml_content:
        yaml_config = OmegaConf.create(yaml.safe_load(yaml_content))

    schema = OmegaConf.structured(config_type)
    config: C = cast(C, OmegaConf.merge(schema, yaml_config))
    return config


@dataclass
class SingleUserEndpointConfig:
    """
    Configuration parameters for an endpoint *set by the user* - in contrast to
    addresses which are usually autogenerated by wizard.
    """

    skip: bool = False
    n_concurrent_rollouts: int = MISSING


@dataclass
class EndpointAddresses:
    """A list of URLs for a single endpoint, usually autogenerated by wizard."""

    addresses: list[str] = MISSING


@dataclass
class NetworkSimulatorConfig:
    """
    Addresses of all endpoints in simulation - this section is usually autogenerated by
    wizard.
    """

    sensorsim: EndpointAddresses = MISSING
    driver: EndpointAddresses = MISSING
    physics: EndpointAddresses = MISSING
    trafficsim: EndpointAddresses = MISSING
    controller: EndpointAddresses = MISSING


@dataclass
class RuntimeCameraConfig:
    """Configuration for a camera in the runtime. See `RuntimeCamera` for more details."""

    logical_id: str = "camera_front_wide_120fov"
    height: int = 160
    width: int = 256
    frame_interval_us: int = 33_000  # about 30fps
    shutter_duration_us: int = 17_000
    first_frame_offset_us: int = 0


@dataclass
class PoseConfig:
    translation_m: tuple[float, float, float]
    rotation_xyzw: tuple[float, float, float, float]


@dataclass
class OpenCVPinholeConfig:
    """OpenCV pinhole parameters (matches sensorsim OpenCVPinholeCameraParam)."""

    focal_length: tuple[float, float]
    principal_point: tuple[float, float]
    radial: tuple[float, ...] = ()  # k1..k6
    tangential: tuple[float, ...] = ()  # p1, p2
    thin_prism: tuple[float, ...] = ()  # s1..s4


@dataclass
class OpenCVFisheyeConfig:
    focal_length: tuple[float, float]
    principal_point: tuple[float, float]
    radial: tuple[float, ...] = ()  # k1..k4
    max_angle: Optional[float] = None


@dataclass
class LinearCdeConfig:
    linear_c: float
    linear_d: float
    linear_e: float


@dataclass
class FthetaConfig:
    principal_point: tuple[float, float]
    reference_poly: str  # Literal["pixel_to_angle", "angle_to_pixel"]
    pixeldist_to_angle: list[float] = field(default_factory=list)
    angle_to_pixeldist: list[float] = field(default_factory=list)
    max_angle: Optional[float] = None
    linear_cde: Optional[LinearCdeConfig] = None


@dataclass
class CameraIntrinsicsConfig:
    model: str  # Literal["opencv_pinhole", "opencv_fisheye", "ftheta"]
    opencv_pinhole: Optional[OpenCVPinholeConfig] = None
    opencv_fisheye: Optional[OpenCVFisheyeConfig] = None
    ftheta: Optional[FthetaConfig] = None


@dataclass
class CameraDefinitionConfig:
    # For NRE sensorsim, overwrite the logical_id of one of the existing
    # cameras: [
    #     'camera_cross_left_120fov',
    #     'camera_cross_right_120fov',
    #     'camera_front_tele_30fov',
    #     'camera_front_wide_120fov'
    # ]
    logical_id: str
    rig_to_camera: PoseConfig
    intrinsics: CameraIntrinsicsConfig
    resolution_hw: tuple[int, int]
    # TODO(migl): Not sure to what extent this field is used.
    # ShutterType is one of: [
    #     "ROLLING_TOP_TO_BOTTOM",
    #     "ROLLING_LEFT_TO_RIGHT",
    #     "ROLLING_BOTTOM_TO_TOP",
    #     "ROLLING_RIGHT_TO_LEFT",
    #     "GLOBAL"
    # ]
    shutter_type: str


class PhysicsUpdateMode(Enum):
    NONE = 0
    EGO_ONLY = 1
    ALL_ACTORS = 2


class RouteGeneratorType(Enum):
    MAP = 0
    RECORDED = 1


@dataclass
class EgomotionNoiseModelConfig:
    enabled: bool = False
    cov_x: float = 0.05  # [m^2 / s]
    cov_y: float = 0.05  # [m^2 / s]
    cov_z: float = 0.0  # [m^2 / s]
    time_constant_position: float = 3.0  # [s]
    cov_orientation_x: float = 0.0  # [rad^2 / s]
    cov_orientation_y: float = 0.0  # [rad^2 / s]
    cov_orientation_z: float = 0.0007  # [rad^2 / s]
    time_constant_orientation: float = 5.0  # [s]


@dataclass
class ScenarioConfig:
    """
    Groups the config parameters of a single scenario.
    A full alpasim config includes an arbitrary number of scenarios to be simulated.
    """

    scene_id: str = MISSING
    n_sim_steps: int = MISSING
    n_rollouts: int = MISSING

    control_timestep_us: int = 100_000
    egopose_interval_us: int = 100_000  # 10 Hz
    force_gt_duration_us: int = 500_000  # 0.5s
    time_start_offset_us: int = (
        250_000  # 0.25s: there are often weird artifacts at the very start of a scene
    )

    # if true, we assert that each call to policy happens immediately after a frame has been
    # provided for each camera and the latest egomotion update. This flag does not modify
    # any parameters, only verifies that the config satisfies this condition (no user misconfiguration).
    # for extra information see the README.
    assert_zero_decision_delay: bool = False

    cameras: list[RuntimeCameraConfig] = field(
        default_factory=lambda: [RuntimeCameraConfig()]
    )

    # if None, the data will be pulled from the .usdz file
    vehicle: Optional[VehicleConfig] = None

    physics_update_mode: PhysicsUpdateMode = PhysicsUpdateMode.NONE

    image_format: str = "jpeg"  # Literal["jpeg", "png"]
    # Rig/directory in ego-hoods to use for ego masking. If None, no ego masking will be done.
    ego_mask_rig_config_id: Optional[str] = None
    planner_delay_us: int = (
        0  # models time delays from image capture to planner output to controller
    )

    egomotion_noise: EgomotionNoiseModelConfig = field(
        default_factory=lambda: EgomotionNoiseModelConfig()
    )

    route_generator_type: RouteGeneratorType = RouteGeneratorType.MAP

    # Whether to send optional messages to the driver
    send_recording_ground_truth: bool = False
    send_av_messages: bool = False

    # Actors that appear for less than this amount of time will be dropped
    # before the simulation starts. Set to 0 to disable filtering.
    min_traffic_duration_us: int = 3_000_000  # 3 s

    # Flag to enable grouping of render requests
    group_render_requests: bool = False


@dataclass
class UserEndpointConfig:
    """User-provided configuration for each of the endpoints"""

    sensorsim: SingleUserEndpointConfig = MISSING
    driver: SingleUserEndpointConfig = MISSING
    physics: SingleUserEndpointConfig = MISSING
    trafficsim: SingleUserEndpointConfig = MISSING
    controller: SingleUserEndpointConfig = MISSING

    sensorsim_cache_size: Optional[int] = None  # Scene cache size for sensorsim
    startup_timeout_s: int = 2 * 60  # 2 minutes by default
    do_shutdown: bool = True


@dataclass
class RoadCastConfig:
    """Configuration for RoadCast output"""

    # Radial distance from the ego to find lanes to write to RoadCast.
    lane_radius: float = 50.0


@dataclass
class UserSimulatorConfig:
    """The section of simulator config created manually by the user"""

    scenarios: list[ScenarioConfig] = MISSING
    save_dir: str = MISSING
    enable_autoresume: bool = False
    endpoints: UserEndpointConfig = MISSING

    roadcast: RoadCastConfig = field(default_factory=lambda: RoadCastConfig())
    smooth_trajectories: bool = True  # whether to smooth trajectories with cubic spline
    extra_cameras: list[CameraDefinitionConfig] = field(default_factory=list)


@dataclass
class SimulatorConfig:
    """
    The entire simulator config consists of two parts, one provided by the user manually
    (`user`) and `network` which is likely autogenerated by the deployment system like wizard.
    """

    user: UserSimulatorConfig = MISSING
    network: NetworkSimulatorConfig = MISSING
